//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.5485
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHelloWorldService")]
public interface IHelloWorldService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/GetMessage", ReplyAction="http://tempuri.org/IHelloWorldService/GetMessageResponse")]
    string GetMessage(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/GetTestContact", ReplyAction="http://tempuri.org/IHelloWorldService/GetTestContactResponse")]
    testContact GetTestContact(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IHelloWorldServiceChannel : IHelloWorldService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class HelloWorldServiceClient : System.ServiceModel.ClientBase<IHelloWorldService>, IHelloWorldService {
    
    public HelloWorldServiceClient() {
    }
    
    public HelloWorldServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public HelloWorldServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public HelloWorldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public HelloWorldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    public string GetMessage(string name) {
        return base.Channel.GetMessage(name);
    }
    
    public testContact GetTestContact(string name) {
        return base.Channel.GetTestContact(name);
    }
}


[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="testContact", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class testContact : object, System.Runtime.Serialization.IExtensibleDataObject {
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string Address1Field;
    
    private string Address2Field;
    
    private string Address3Field;
    
    private string ContactCodeField;
    
    private string EmailField;
    
    private string PhoneField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
        get {
            return this.extensionDataField;
        }
        set {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Address1 {
        get {
            return this.Address1Field;
        }
        set {
            this.Address1Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Address2 {
        get {
            return this.Address2Field;
        }
        set {
            this.Address2Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Address3 {
        get {
            return this.Address3Field;
        }
        set {
            this.Address3Field = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ContactCode {
        get {
            return this.ContactCodeField;
        }
        set {
            this.ContactCodeField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Email {
        get {
            return this.EmailField;
        }
        set {
            this.EmailField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Phone {
        get {
            return this.PhoneField;
        }
        set {
            this.PhoneField = value;
        }
    }
}
